const Router = require('express')
const router=new Router()
const answerRouter = require('./answerRouter')
const catalogRouter = require('./catalogRouter')
const taskRouter = require('./taskRouter')
const chapterRouter = require('./chapterRouter')
const readChapterRouter = require('./readChapterRouter')
const userRouter = require('./userRouter')
const readThemesRouter = require('./readThemesRouter')
const testRouter = require('./testRouter')
const subjectRouter = require('./subjectRouter')
const planRouter = require('./planRouter')
const themesRouter = require('./themesRouter')
const chapterContentRouter = require('./chapterContentRouter')
const resultStudentRouter = require('./resultStudentRouter')
const glossaryRouter = require('./glossaryRouter')



router.use('/user',userRouter)
router.use('/task',taskRouter)
router.use('/themes',themesRouter)
router.use('/test',testRouter)
router.use('/answer',answerRouter)
router.use('/catalog',catalogRouter)
router.use('/chapter',chapterRouter)
router.use('/subject',subjectRouter)
router.use('/plan',planRouter)
router.use('/readChapter',readChapterRouter)
router.use('/readThemes',readThemesRouter)
router.use('/chapterContent',chapterContentRouter)
router.use('/resultStudent',resultStudentRouter)
router.use('/glossary',glossaryRouter)

module.exports = router